disabled_rules:
  - file_length
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - identifier_name
  - multiple_closures_with_trailing_closure
  - operator_usage_whitespace
  - trailing_closure
  - type_body_length
  - type_name
  - nesting
  - opening_brace
  - missing_docs
  - file_header
  - colon
  - file_name
