---
openapi: 3.0.3
info:
  title: Geräte Management Service (GMS) TLS API
  version: '1.0'
  description: TLS endpoints of the GMS

servers:
  - url: https://dsr.gms.dev.gematik.solutions
    description: LTU DEV environment

paths:
  /nonce:
    get:
      description: 'Method to obtain a nonce'
      tags:
        - Nonce
      responses:
        "200":
          description: 'Nonce successfully created'
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: 'Internal Server Error'

  /register-device:
    post:
      description: 'Method to register a device'
      tags:
        - Register Device
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterDeviceRequest'
      responses:
        "201":
          description: 'Device successfully registered'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterDeviceResponse'
        "400":
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebServiceError'
        "500":
          description: 'Internal Server Error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebServiceError'

components:
  schemas:
    RegisterDeviceRequest:
      required:
        - token
      type: object
      properties:
        token:
          type: string
          description: 'Device Registration Token'

    RegisterDeviceResponse:
      required:
        - cert
      type: object
      properties:
        cert:
          type: string
          description: 'mTLS certificate - base64 DER'

    WebServiceError:
      required:
        - errorCode
        - description
        - traceId
      type: object
      properties:
        errorCode:
          type: string
          description: 'Identifier / code of the error / exception'
        description:
          type: string
          description: 'Description of the error / exception'
        traceId:
          type: string
          format: uuid
          description: 'Id to track the error / exception'
